 
- include_tasks: arch-tasks.yml
  when: ansible_os_family == "Archlinux"

- include_tasks: debian-tasks.yml
  when: ansible_os_family == "Debian"

#- include_tasks: macos-tasks.yml
#  when: ansible_os_family == "Darwin"

# Pulled from these stackoverflow conversations:
# https://unix.stackexchange.com/questions/705401/delete-all-target-links-and-files-before-running-gnu-stow
# https://unix.stackexchange.com/questions/680413/opposite-of-adopt-option-for-gnu-stow
- name: Get list of dotfiles to check for GNU Stow conflicts
  shell: find ./home/{{ item }} \( -type f -o -type l \) | sed 's/.\/home\/{{ item }}\///g'
  args:
    chdir: ~/dotfiles
  register: conflict_files
  with_items:
    - plasma

- name: Show list of files to be checked for GNU Stow conflicts
  debug:
    var: conflict_files

- name: Delete conflicting files
  shell: rm -rf ~/{{ item }}
  with_items: "{{ conflict_files.stdout_lines }}"

- name: Symlink rofi dotfiles
  shell: stow --no-folding -d ~/dotfiles/home -t ~/ {{ item }}
  with_items:
    - plasma
