- name: Update pacman cache
  become: yes
  community.general.pacman:
    update_cache: true

- name: If Arch Linux, install GNU Stow with pacman
  become: yes
  community.general.pacman:
    name: stow
    state: present

- command: "awk '{print $1}' '{{playbook_dir}}/core/pkglist.txt'"
  register: _pkgs
  delegate_to: localhost
  run_once: true

- name: Install packages from pkglist.txt
  become: yes
  community.general.pacman:
    name: "{{ _pkgs.stdout_lines }}"
    state: present

- name: Packages from pkglist.txt list debug message
  debug:
    msg: "{{ _pkgs.stdout_lines }}"

- name: Install paru dependencies
  community.general.pacman:
    name:
      - git
      - base-devel
      - rustup
    state: present

- name: Check if paru exists
  stat:
    path: /usr/bin/paru
  register: paru_exists

- name: Install stable version of rust
  become: no
  command: rustup install stable
  when: paru_exists.stat.exists == false

- name: Set default version of cargo to stable
  become: no
  command: rustup default stable
  when: paru_exists.stat.exists == false

- name: Install paru
  become: yes
  kewlfft.aur.aur:
    name: paru
    use: makepkg
    state: present
  when: paru_exists.stat.exists == false

- name: Install pacdef from AUR using paru
  kewlfft.aur.aur:
    use: paru
    name:
      - pacdef
    state: present

- name: Register packages from aur_pkglist.txt
  command: "awk '{print $1}' '{{playbook_dir}}/core/aur_pkglist.txt'"
  register: _aur_pkgs
  delegate_to: localhost
  run_once: true

- name: Packages from aur_pkglist.txt list debug message
  debug:
    msg: "{{ _aur_pkgs.stdout_lines }}"

- name: Install packages from aur_pkglist.txt
  kewlfft.aur.aur:
    use: paru
    name: "{{ _aur_pkgs.stdout_lines }}"
    state: present