- name: Update pacman cache
  become: yes
  community.general.pacman:
    update_cache: true

- name: If Arch Linux, install GNU Stow with pacman
  when: ansible_os_family == "Archlinux"
  community.general.pacman:
    name: stow
    state: present

- command: "awk '{print $1}' '{{role_path}}/pkglist.txt'"
  register: _pkgs
  delegate_to: localhost
  run_once: true

- name: Install packages from pkglist.txt
  become: yes
  community.general.pacman:
    name: "{{ _pkgs.stdout_lines }}"
    state: present

- name: Setup AUR helper
  become: yes
  community.general.pacman:
    name: paru
    state: present

- name: Install pacdef from AUR using paru
  kewlfft.aur.aur:
    use: paru
    name:
      - pacdef
    state: present