- name: Update pacman cache
  become: yes
  community.general.pacman:
    update_cache: true

- name: Install vim
  become: yes
  community.general.pacman:
    name: vim
    state: present

- name: Install ctags
  become: yes
  community.general.pacman:
    name: ctags
    state: present