- name: Update pacman cache
  become: yes
  community.general.pacman:
    update_cache: true

- name: Install zsh
  become: yes
  community.general.pacman:
    name: zsh
    state: present

- name: Symlink zsh dotfiles
  shell: stow -d ~/dotfiles/home -t ~/ {{ item }}
  with_items:
    - zsh
