- name: Update pacman cache
  become: yes
  community.general.pacman:
    update_cache: true

- command: "awk '{print $1}' '{{role_path}}/pkglist.txt'"
  register: _pkgs
  delegate_to: localhost
  run_once: true

- name: Install packages from pkglist.txt
  community.general.pacman:
    name: "{{ _pkgs.stdout_lines }}"
    state: present

- name: Create the `aur_builder` user per kewlfft.aur
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
<<<<<<< HEAD
<<<<<<< HEAD
  community.general.pacman:
    name: docker
    state: present

- name: Install docker-compose
  become: yes
  community.general.pacman:
    name: docker-compose
    state: present

- name: Install docker-compose
  become: yes
  community.general.pacman:
    name: tmux
    state: present

- name: Install thefuck
  become: yes
  community.general.pacman:
    name: thefuck
    state: present

- name: Create the `aur_builder` user per kewlfft.aur
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
=======
>>>>>>> 8d14638 (Added kubernetes and other tweaks to emacs config)
=======
>>>>>>> 8d14638 (Added kubernetes and other tweaks to emacs config)
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf '
