- include_tasks: arch-tasks.yml
  when: ansible_os_family == "Archlinux"

- include_tasks: debian-tasks.yml
  when: ansible_os_family == "Debian"

- include_tasks: macos-tasks.yml
  when: ansible_os_family == "Darwin"
