- name: Update pacman cache
  become: yes
  community.general.pacman:
    update_cache: true

- name: Install espanso
  kewlfft.aur.aur:
    use: paru
    name:
      - espanso

- name: Symlink espanso dotfiles
  shell: stow --no-folding -d ~/dotfiles/home -t ~/ {{ item }}
  with_items:
    - espanso
