---
- hosts: localhost
  connection: local
  remote_user: "{{ localuser }}"
  vars:
    user: "{{ localuser }}"
  roles:
    - core
    - zsh
    - emacs
    - espanso
    # - plasma
    # - themeing
    # Bash is broken on fresh arch installs because stow doesn't want to override existing .bashrc:
    - bash
    # - weechat
    - xonsh
    - vim
    - swhkd
    - eww
    - rofi
    # - tmux
    # - xresources
    # - wanderlust
    # - exwm
