;;; package --- Main init file
;;; Commentary:
;;; 	The first version of this init file was generated by emacs-bootstrap,
;;;	and then I added my own elisp using org-babel (config.org).
;;;     https://github.com/editor-bootstrap/emacs-bootstrap

;;; Code:

(add-to-list 'load-path (concat user-emacs-directory "elisp"))
;; (add-to-list 'default-frame-alist '(fullscreen . maximized))
(setq vc-follow-symlinks t)

;;; My configuation using org-babel
(org-babel-load-file "~/.emacs.d/babel/config.org")
